language: dart

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

dart_task:
  - test: --platform vm

  # Warnings are fatal, but we only analyze the lib/ directory.
  - dartanalyzer: --fatal-warnings lib

cache:
  directories:
    - "$HOME/.pub-cache"
